baseURL: "https://wiki.ledstrain.org/"
title: "LEDStrain Wiki"
theme: "book"

# Book configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    startLevel: 1

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
languages:
  en:
    languageName: English
    contentDir: content
    weight: 1
    #  ru:
    #    languageName: Russian
    #    contentDir: content.ru
    #    weight: 2
    #  cn:
    #    languageName: Chinese
    #    contentDir: content.cn
    #    weight: 3

params:
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  BookToC: 3

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  # BookLogo: /logo.png

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle: /menu

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
  BookSection: docs

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/ledstrain/wiki.ledstrain.org

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: blob/master/content

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "Jan 2, 2006"

  # (Optional, default true) Enables search function with flexsearch,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch: true

  # Shortcode
  # forum-post
  postLength: "300"

caches:
  getjson: 
    # Reset json cache every month
    # This will refresh permalinked comments with forum-post shortcode
    maxAge: "720h"

